package com.hw1.app.covid_service.selenium;

import static org.assertj.core.api.Assertions.assertThat;

import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.extension.ExtendWith;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.FindBy;

import io.github.bonigarcia.seljup.SeleniumJupiter;

@ExtendWith(SeleniumJupiter.class)
public class Hw1Test {

  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  private final String URL = "localhost:4200";

  @FindBy(name="country")
  private WebElement country;

  @FindBy(id="month")
  private WebElement month;

  @FindBy(name="search")
  private WebElement search;

  @FindBy(css="label:nth-child(2)")
  private WebElement label2;

  @FindBy(css="label:nth-child(4)")
  private WebElement label4;

  @FindBy(css="label:nth-child(6)")
  private WebElement label6;

  @FindBy(css="label:nth-child(8)")
  private WebElement label8;

  @FindBy(id="selected_country")
  private WebElement selected_country;

  @BeforeEach
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @AfterEach
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void seleniumTest() {

    driver.get("http://localhost:4200/");
    driver.manage().window().setSize(new Dimension(1846, 1053));
    assertThat(driver.getTitle()).isEqualTo("Covid-19");

    country.click();
    country.sendKeys("usa");
    month.click();

    assertThat(selected_country.getText()).isEqualToIgnoringCase("usa");
    
    search.click();
    driver.manage().timeouts().implicitlyWait(3, TimeUnit.SECONDS);

    label8.click();
    search.click();

    driver.manage().timeouts().implicitlyWait(3, TimeUnit.SECONDS);

    label4.click();
    search.click();

    driver.manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);

    label6.click();
    search.click();

    driver.manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);

    country.sendKeys("france");
    label4.click();
    search.click();

    driver.manage().timeouts().implicitlyWait(3, TimeUnit.SECONDS);

    assertThat(selected_country.getText()).isEqualToIgnoringCase("france");

    label2.click();
    search.click();

    driver.manage().timeouts().implicitlyWait(3, TimeUnit.SECONDS);

    label4.click();
    search.click();

    driver.manage().timeouts().implicitlyWait(2, TimeUnit.SECONDS);

  }
}
