name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Running verify Maven lifecycle
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Docker compose - build all services
        run: docker-compose build
      - name: Docker compose - run 'Angular' service
        run: docker-compose build angular
      - name: Verify lifecycle and tests
        run: mvn -B clean verify
        working-directory: ./covid_service
    
